// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: contracts/Counter.vy → .build/__local__.json

export const counterAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "caller",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "new_count",
        "type": "uint256"
      }
    ],
    "name": "Incremented",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "increment",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "reset",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "count",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
] as const
export type CounterAbi = typeof counterAbi

export const counterBytecode = "0x3461001957335f5561014961001d61000039610149610000f35b5f80fd5f3560e01c60026003820660011b61014301601e395f51565b63d09de08a811861013b573461013f576001546001810181811061013f579050600155337f38ac789ed44572701765277c4d0970f2db1c1a571ed39e84358095ae4eaa542060015460405260206040a260015460405260206040f35b63d826f88f8118610104573461013f575f543318156100fe5760208060a05260096040527f6e6f74206f776e6572000000000000000000000000000000000000000000000060605260408160a001602982825e8051806020830101601f825f03163682375050601f19601f8251602001011690509050810190506308c379a060805280600401609cfd5b5f600155005b638da5cb5b811861013b573461013f575f5460405260206040f35b6306661abd811861013b573461013f5760015460405260206040f35b5f5ffd5b5f80fd00740018011f855820ab5e470560bf0da1e2df7984d76a471a322da3b0e790791934e819e4523769d8190149810600a1657679706572830004030036" as `0x${string}`
