// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit.

import { coinMintableAbi, coinMintableBytecode } from './CoinMintable'
import { counterAbi, counterBytecode } from './Counter'
import { nftGraphicAbi, nftGraphicBytecode } from './NFTGraphic'
import { nftMinterAbi, nftMinterBytecode } from './NFTMinter'
import { nftMinter1155Abi, nftMinter1155Bytecode } from './NFTMinter1155'
import signatures from './signatures.json'

export const contracts = {
  CoinMintable: { abi: coinMintableAbi, bytecode: coinMintableBytecode, signatures: signatures.CoinMintable },
  Counter: { abi: counterAbi, bytecode: counterBytecode, signatures: signatures.Counter },
  NFTGraphic: { abi: nftGraphicAbi, bytecode: nftGraphicBytecode, signatures: signatures.NFTGraphic },
  NFTMinter: { abi: nftMinterAbi, bytecode: nftMinterBytecode, signatures: signatures.NFTMinter },
  NFTMinter1155: { abi: nftMinter1155Abi, bytecode: nftMinter1155Bytecode, signatures: signatures.NFTMinter1155 },
} as const

export type ContractName = keyof typeof contracts

export { coinMintableAbi, coinMintableBytecode } from './CoinMintable'
export { counterAbi, counterBytecode } from './Counter'
export { nftGraphicAbi, nftGraphicBytecode } from './NFTGraphic'
export { nftMinterAbi, nftMinterBytecode } from './NFTMinter'
export { nftMinter1155Abi, nftMinter1155Bytecode } from './NFTMinter1155'
