export const DAY6_SPEAKER_NOTES = [
  // 1. Cover
  "Cover slide. Open by reminding students of the question that closed Day 5: Bitcoin scripts can verify a signature, but cannot run general programs. Day 6 covers two extensions to that idea. The first is a different way to secure the chain (Proof of Stake). The second is a different idea about what the chain can do (run smart contracts).",
  // 2. Agenda
  "Agenda. Four sections. Part 1 covers the limits of Proof of Work and how Ethereum's Proof of Stake addresses them. Part 2 compares the two consensus mechanisms directly. Part 3 introduces smart contracts and the Solidity language. Part 4 looks at examples of applications built on Ethereum.",
  // 3. Bridge from Day 5
  "Bridge from Day 5. Bitcoin Script is intentionally limited. Roughly 100 instructions support signature verification, hash checks, time locks, and multi-signer requirements. It does not support loops, persistent storage, or calls between scripts. Ethereum took the opposite design choice. The Ethereum Virtual Machine, or EVM, is Turing-complete. Any program a general-purpose programming language can express can run on Ethereum.",
  // 4. Part 1 Divider
  "Part 1 setup. Rather than open with the answer, open with the problem. Bitcoin's Proof of Work is an elegant security model, but it has two significant limitations. The first is energy cost. The second is the risk that mining power concentrates in a small number of pools. Students need to feel both problems before Ethereum's solution will land.",
  // 5. PoW Recap
  "Proof of Work recap. Day 3 covered this in depth. Quick refresher: miners compete to find a number called a nonce. The nonce, when combined with the block's contents and hashed, must produce a hash starting with a target number of leading zeros. Miners try billions of nonces per second using specialized ASIC hardware. The first miner to find a valid nonce broadcasts the block and earns the reward. The chain is secure because rewriting an old block would require redoing all of that work faster than the rest of the network combined.",
  // 6. Energy Problem (Limitation 1)
  "Limitation 1: energy consumption. Bitcoin currently consumes roughly 150 TWh per year, comparable to Argentina's annual electricity use. Pre-Merge Ethereum consumed about 78 TWh per year, comparable to Chile. The key conceptual point: increasing the network's hashrate (its total mining power) does not make the chain process transactions any faster. It only increases the electricity required to keep the chain at the same level of security. The energy cost grows in proportion to the security budget. Do not reveal the post-Merge drop on this slide; that is the payoff on the Merge slide later.",
  // 7. The 51% Attack (Limitation 2)
  "Limitation 2: mining-power concentration. Define the attack: if a single party (or coordinated group) controls more than 50% of the network's hashrate, they can decide which blocks the network accepts. With majority hashrate, an attacker can rewrite recent blocks, double-spend coins they have already paid out, or refuse to include certain transactions. Define double-spend on the slide: spending the same coins twice by replacing the block that recorded the first payment. Bitcoin's defense is decentralization, but the protocol does not enforce it. The chart shows that the top three pools control approximately 69% of total hashrate. Their security comes from those pools choosing to compete rather than collude.",
  // 8. Real-World Case: Litecoin Reorg (April 2026)
  "Recent real-world example. On April 25, 2026, Litecoin experienced a 13-block reorganization, rolling back roughly 32 minutes of activity. It was the largest reorg on a top-twenty cryptocurrency in roughly five years. The mechanism is the most important thing for students to understand. There were two separate flaws being exploited at the same time. First, a consensus bug in MWEB, Litecoin's MimbleWimble privacy extension, had been privately patched between March 19 and 26 but had not been broadcast publicly or required of all mining pools, so some pools were running the corrected code and some were still running the vulnerable code. Second, a denial-of-service vulnerability allowed the attacker to flood and disable specific mining pools. The attacker combined them: they used the DoS flood to knock the patched pools offline, leaving only the unpatched pools producing blocks. The unpatched pools accepted invalid MWEB transactions as valid, and the attacker used those transactions to peg coins out to outside exchanges before the network corrected itself. Once the DoS subsided, the patched pools came back online, regained majority hashrate, and the network automatically reorganized to the valid chain (the chain without the bad transactions). The 13 invalid blocks were replaced. The pedagogical point to land: a 51% attack does not require permanently acquiring more than half the hashrate. It can also be manufactured by silencing the honest majority for long enough that the dishonest minority becomes the only voice in the room. The Cryptopolitan article linked on the slide is a good short read for students who want the timeline; the CoinDesk piece (linked from speaker notes only) covers the disclosure controversy around the privately patched fix.",
  // 9. PoS Introduction (Ethereum's alternative)
  "Ethereum's Proof of Stake. Both Proof of Work limitations have a common cause: the chain's security depends on physical work, which means electricity and specialized hardware. In Proof of Stake, validators replace miners. A validator is a participant who has locked up an amount of ETH as collateral. That locked-up ETH is called the validator's stake. The protocol selects one validator at random to propose each block, weighted by stake. Other validators submit attestations confirming the block is valid. To attack the chain, an attacker must own a substantial fraction of the staked ETH that the protocol could then destroy.",
  // 10. PoS Lifecycle
  "How a block is added to the chain. This slide gives the full proof-of-stake lifecycle in six steps; the next two slides drill into specific parts (the validator lottery, then slashing and finality). Walk through the timeline: a slot is 12 seconds, when the proposer is picked and the block is built; an epoch is 32 slots, about 6.4 minutes, when committee votes accumulate; finality is reached after two epochs, about 12.8 minutes total, once validators representing 2/3 of all staked ETH have attested. Two definitions students often miss. A committee is a rotating subset of validators (about 1 in 32 of the network) that votes for one specific slot. Slashing applies only to provable cheating, like signing two conflicting blocks; an honest mistake or a bad-but-honest proposal is simply ignored, not slashed. The 2/3 finality threshold (not 50%) is worth saying out loud, because students often assume the threshold is a simple majority.",
  // 11. PoW vs PoS Demo
  "Per-block energy comparison. Click 'Run round' to animate one round of each mechanism. The Proof of Work side shows three miners cycling through random nonces for about 1.5 seconds; one is highlighted as having found a valid block. The Proof of Stake side picks a validator immediately, weighted by stake. The energy counter on the PoW side jumps by ~30,000 kWh per round and the PoS counter by ~1 kWh; these are real per-block estimates for pre-Merge versus post-Merge Ethereum (pre-Merge: ~78 TWh/yr ÷ ~2.6M blocks/yr; post-Merge: ~2,600 MWh/yr ÷ ~2.6M blocks/yr per the Ethereum Foundation). 30,000 kWh is enough to power an average American home for nearly 3 years (EIA 2022: average residential customer used 10,791 kWh/yr); 1 kWh runs a TV for about ten hours. Run 5 to 10 rounds for the contrast to land, then point out that this is the same network before and after the Merge (covered two slides from now).",
  // 12. Validator Lottery
  "Validator selection rule. For each new block, the protocol picks one validator at random; each validator's probability equals their stake divided by the total ETH staked. Click 'Select proposer' to draw one validator; click '+10 rounds' to draw ten at once. Each row shows the observed selection percentage and count alongside the expected percentage. With 5 to 10 selections the observed numbers will look noisy; with 100 to 200 they should track the expected percentages closely. This is the right place to mention the law of large numbers.",
  // 13. Slashing & Finality
  "Slashing and finality. Define both terms on the slide. Slashing is the protocol's automatic penalty for validator misbehavior; if a validator signs two conflicting blocks, the protocol destroys part of their stake and removes them from the validator set. A coordinated attack would require many validators to be slashed at once, destroying roughly one third of all staked ETH (currently tens of billions of dollars). Finality is the point at which a block is treated as permanent and cannot be reversed. Ethereum finalizes blocks after two epochs, approximately 12.8 minutes. Bitcoin has no formal finality concept; users typically wait for around six confirmations (approximately 60 minutes) before treating a transaction as effectively final. The asymmetry to highlight: a failed attack in Proof of Work costs the attacker electricity already spent. A failed attack in Proof of Stake costs the attacker their own stake.",
  // 14. Part 2 Divider
  "Part 2 setup. Both consensus mechanisms achieve similar security goals through different physical and economic resources. The next two slides compare them directly: a six-row table of attributes, then the historical event when Ethereum switched from one to the other.",
  // 15. PoW vs PoS Table
  "Direct comparison. Energy use is the largest visible difference, but each row matters. PoS finalizes blocks much faster than Bitcoin's de-facto convention of waiting for six confirmations. The hardware requirement collapses from specialized ASICs to a consumer-grade computer. The 51% attack cost flips: in PoW the attacker buys hardware and electricity; in PoS the attacker must acquire and stake the asset that the protocol can then destroy through slashing. The decentralization concern shifts from where mining happens to who holds the most ETH.",
  // 16. The Merge
  "The Merge. On September 15, 2022, Ethereum changed its consensus mechanism from Proof of Work to Proof of Stake. Ethereum had operated under Proof of Work since 2015. The Beacon Chain, a parallel Proof of Stake chain, had been running since December 2020 to test the new mechanism. On Merge day, the two chains combined; mining stopped at block 15,537,393, and from the next block onward validators produced the chain. The transition occurred without downtime, without splitting the chain, and without affecting account balances. Ethereum's annual electricity consumption fell by approximately 99.95%, from about 78 TWh to roughly 0.01 TWh. This is the payoff for the energy slide earlier.",
  // 17. Part 3 Divider
  "Part 3 setup. Part 1 and Part 2 covered how the chain is secured. Part 3 covers what the chain can do. Bitcoin Script supports a limited set of validation operations; the Ethereum Virtual Machine is a general-purpose programming environment. The next several slides define smart contracts, explain how the EVM executes them, and walk through three Solidity examples.",
  // 18. Bitcoin vs Ethereum Scripts
  "Comparing the two scripting environments. Bitcoin Script is a stack-based instruction set of roughly 100 operations. It supports verifying a signature, checking a hash, enforcing a time lock, and requiring multiple signers. It does not support loops, persistent storage between transactions, or calls to other scripts. The Ethereum Virtual Machine is Turing-complete: it supports loops, conditionals, function calls, persistent storage, and calls between contracts. Because programs can in principle run for an unbounded amount of time, every operation costs gas, paid by the user submitting the transaction. Define gas as a unit of computational work; the price of a unit is set by the user. The next slide defines smart contracts; the slide after that explains how they are executed.",
  // 19. What is a Smart Contract
  "Definition of a smart contract. A smart contract is a program stored on the Ethereum blockchain. The contract has its own Ethereum address and can hold a balance of ETH. Any user can call its functions by submitting a transaction. When the contract runs, every node on the network executes the same code in the same order and updates its copy of the contract's on-chain state. The vending machine analogy is informal: the user supplies the required input (a payment), and the contract automatically produces the agreed output, with no human intervention required. The four properties on the right (public, immutable, trustless, composable) are how the rest of the deck will refer back to smart contracts.",
  // 20. The EVM
  "The Ethereum Virtual Machine. Define EVM on the slide. Every Ethereum node runs the same virtual machine. When a transaction is submitted, every node independently executes the contract code on its own copy of the EVM and computes the resulting state. The nodes must reach the same result. This replicated execution, not any single server, is what makes a contract's behavior trustless. Walk through the diagram: a transaction enters the EVM, the EVM executes opcodes (with example operations PUSH, SLOAD, ADD, SSTORE), and the world state is updated accordingly.",
  // 21. Solidity Example 1: SimpleStorage
  "Solidity example 1. The simplest possible contract: one stored value plus a setter and a getter. Frame this for Java students. A contract is comparable to a Java class. uint256 is an unsigned 256-bit integer (Java's long is 64-bit signed, much smaller). The variable 'value' is a state variable, which is the Solidity term for an instance variable that persists on the blockchain between transactions. public and private are the same access modifiers used in Java. view is a Solidity-only modifier indicating that the function does not modify state, so calling it costs no gas. pragma selects the compiler version and has no direct Java equivalent. Reading is free; writing costs gas because it permanently changes the chain's state.",
  // 22. Solidity Example 2: CoffeeShop
  "Solidity example 2. The contract sells coffee. Customers send ETH to call buyCoffee. The contract records how many coffees each address has bought. Only the deploying account can withdraw the collected ETH. New concepts to define: mapping(address => uint256) is a key-value store on the blockchain, comparable to Java's HashMap<Address, Long>. payable is a modifier allowing a function to receive ETH; Java methods cannot receive money in this way. msg.sender and msg.value are built-in variables holding the caller's address and the ETH attached to the call, comparable to data Java code receives through an HttpServletRequest. require(condition, message) checks the condition; if it is false, the entire transaction reverts and no state changes are saved (similar to throwing an exception in Java, but the exception undoes everything). constructor runs once when the contract is deployed, with the same purpose as a Java constructor.",
  // 23. Solidity Example 3: ERC-20 transfer
  "Solidity example 3. ERC-20 is a standard interface for tokens on Ethereum. Tokens such as USDC, DAI, and UNI all implement the same set of methods. Comparable to Java's List interface: many implementations, one shared contract. The transfer function performs three steps: validate input with require, update state by modifying balances, and log the result with emit. This is the same shape as a typical Java service method (validate, mutate, log). Define event as a structured log entry stored with the transaction, similar in spirit to System.out.println but readable by any program watching the blockchain. emit fires the event, comparable to publishing to a Java event bus. indexed adds a search index to a field of the event, similar to indexing a database column. Because every ERC-20 token uses the same interface, any wallet can display any token.",
  // 24. Vending Machine Demo
  "Vending machine demonstration. The contract code from Example 2 is on the left; the interactive caller UI is on the right. Use the 'You are' toggle to switch between owner and customer accounts. Calling buyCoffee with 0.01 ETH succeeds (contract balance and the caller's coffee count both go up). Calling buyCoffee with 0.005 ETH triggers the require check and reverts; no state changes. Calling withdraw as owner clears the contract balance; as customer it reverts with the 'Only owner' message. The event log shows successes in green and reverts in red. The teaching beat to land: a reverted transaction does not just refuse the action, it undoes every state change made earlier in the same transaction.",
  // 25. Gas and Fees
  "Gas and fees. Define gas as the unit used to measure the computational work an operation requires on the EVM. Every EVM opcode has a fixed gas cost. ADD costs 3 gas; SSTORE (writing to storage) costs 20,000 gas, much higher because every node must store the new value forever. The total fee for a transaction is gas units used multiplied by the gas price. The gas price is paid in gwei; 1 gwei equals 0.000000001 ETH. Gas serves two purposes: first, it bounds execution (a runaway program runs out of gas and the transaction reverts); second, it prices network demand (when the network is congested, gas prices rise as users compete by bidding higher prices).",
  // 26. Part 4 Divider
  "Part 4 setup. The previous parts covered consensus and the contract execution model. Part 4 looks at examples of applications that have been built on smart contracts. Each example reconstructs a familiar service (an exchange, a name service, a lending protocol) without a central operator.",
  // 27. ERC-20 Demo + Etherscan
  "ERC-20 transfer demonstration. Alice starts with 1,000 TOKEN; Bob starts with 0. Drag the slider to set an amount, then click Transfer. On success, the wallet balances update and the Etherscan-style receipt on the right populates with a block number, fake transaction hash, gas used, and the Transfer event. Slide past 1,000 to trigger the require revert (insufficient balance); the status badge switches to Reverted, the gas value drops (a reverted tx still costs gas), and balances do not change. The 'View a real ERC-20 transfer on etherscan.io' link at the bottom opens an actual on-chain transfer so students can confirm what the data looks like on the public block explorer.",
  // 28. Ecosystem Tour
  "Application examples. Four cards covering four representative systems. Uniswap is a decentralized exchange; the contract lets users trade tokens directly, with prices set by a formula based on the relative supply of two tokens held by the contract. OpenSea is an NFT marketplace; each sale is a smart contract call that transfers ownership of a unique on-chain token. ENS is the Ethereum Name Service; it maps human-readable names like vitalik.eth to Ethereum addresses, similar to how DNS maps domain names to IP addresses. Aave is a lending protocol; users deposit tokens as collateral, borrow other tokens against the collateral, and the contract sets interest rates based on supply and demand.",
  // 29. Real Risks
  "Limitations and failure modes. Three concrete risk patterns. Re-entrancy: a contract calls another, which calls back into the first before its first call has finished; if state updates are out of order, funds can be withdrawn twice. The 2016 DAO incident drained approximately $60 million in ETH this way. Rug pulls: a team deploys a token, attracts deposits, then drains the contract or removes liquidity; the contract usually executes exactly as written, and the deception is in what the team chose not to disclose. Immutability: deployed code cannot be modified, so a bug in production cannot be patched the way a bug in a typical web application can; standard responses are deploying a corrected contract and migrating users, or building upgrade patterns into the contract from the start. The tradeoff to make explicit: a system that cannot be censored or rewritten by any single party is also a system in which mistakes are permanent.",
  // 30. Recap
  "Summary. Three concepts to make sure students take away. First: Proof of Stake. Validators replace miners; security depends on the value of staked ETH rather than electricity consumption; the Merge of September 2022 reduced energy use by approximately 99.95% without disrupting the chain. Second: smart contracts. Ethereum extends Bitcoin's scripting model into a Turing-complete programming environment; programs deployed to the chain run identically on every node, which is what gives their results global consensus. Third: open deployment. Any user with an Ethereum account and enough ETH for the gas fee can deploy a smart contract; the barrier to launching a financial application is much lower than for the equivalent traditional system.",
  // 31. Next Class
  "Next class. Three options on the table for Day 7. Option 1: writing and deploying a small Solidity contract using Remix or a similar in-browser environment. Option 2: examining Layer 2 scaling solutions (rollups) and zero-knowledge proofs. Option 3: exploring decentralized identity systems (such as ENS, Sign in with Ethereum, or DID standards). Ask students which direction is most interesting before committing.",
]
