export const DAY5_SPEAKER_NOTES = [
  "Cover — Day 5: Lightning Networks. Open with the question: if Bitcoin is so great, why can't you use it to buy a $4 coffee? The answer is speed, and Lightning is Bitcoin's answer.",
  'Agenda — four questions, four parts. We trace from Bitcoin’s 7 TPS ceiling all the way to a planet-scale payment network. Each part builds on the last.',
  'Part 1 bridge — Before Lightning makes sense, we need to feel the problem. Bitcoin is deliberately slow — and the numbers compared to Visa are jarring.',
  "The numbers say it all. Visa processes 4,000 TPS normally, with a hardware ceiling of 65,000. Bitcoin: 7 TPS. The 1 MB block limit and 10-minute block time are the bottleneck. Ask: why doesn't Bitcoin just raise the block size?",
  'Scalability — Bigger blocks mean fewer people can run full nodes, which threatens decentralization. So Bitcoin deliberately keeps blocks small. To go faster, we need a layer that doesn’t use the blockchain for every payment.',
  "Part 2 bridge — Lightning's answer: don't put every transaction on the blockchain. Open a private bilateral ledger and settle only the final balance on-chain.",
  "Lightning is a second layer. It doesn't change Bitcoin's rules — it adds a channel abstraction on top. Think of running a tab at a bar: you don't pay for each drink, you settle once at the end.",
  'Opening a channel means establishing a direct private line between two parties. Bob and the Coffeeshop agree to transact. The channel is their shared, cryptographically secured ledger.',
  'The funding mechanism is a 2-of-2 multi-signature Bitcoin address. Bob locks 0.05 BTC in the shared address. Neither party can spend the funds without both signatures — cryptographic escrow, no middleman.',
  'The first balance sheet is signed by both parties. Bob will get: 0.05 BTC. Coffeeshop will get: 0 BTC. Both sign and keep a copy. This is their mutual agreement about the current state of funds.',
  'Opening the channel requires exactly one blockchain transaction: the funding tx. After confirmation, Bob and the Coffeeshop can exchange millions of payments without ever touching the blockchain again.',
  'Part 3 bridge — How do payments actually happen inside the channel? And what stops either party from cheating by submitting an old, more favorable balance sheet?',
  'Every coffee purchase is an off-chain update. Bob pays 0.005 BTC for a coffee. He and the Coffeeshop agree on new balances: Bob 0.045, Coffeeshop 0.005. No blockchain transaction. No fee. Instant.',
  'Each new balance sheet supersedes the previous one. Both cross out the old numbers, write new ones, and both sign. The replacement is bilateral — neither can update unilaterally.',
  "After each update, both parties exchange signed copies. Bob holds the Coffeeshop's signature on the latest sheet; the Coffeeshop holds Bob's. Neither can unilaterally claim old balances.",
  'To close the channel, either party broadcasts the latest signed balance sheet. The multi-sig releases funds: Bob 0.045 BTC, Coffeeshop 0.005 BTC. Total on-chain transactions: 2 — open and close.',
  '100 coffees, 2 blockchain transactions. The whole point. The bottleneck never applies because the chain was never involved. Fees paid once. Confirmation latency paid once.',
  'What stops Bob from broadcasting an earlier sheet where he had 0.05 BTC? The revocation mechanism: if a revoked sheet is broadcast, the other party can claim the entire channel balance. Cheating is self-defeating.',
  'Part 4 bridge — Two-party channels are useful. But channels chaining together is the real breakthrough. The Lightning Network routes payments across chains of channels.',
  "Alice and Bob open their own channel. Bob also has a channel with the Coffeeshop. Alice doesn't need a direct channel with the Coffeeshop to pay it.",
  'Alice can pay the Coffeeshop by routing through Bob. Alice’s channel with Bob updates; Bob’s channel with the Coffeeshop updates — atomically. Bob earns a tiny routing fee.',
  'The mechanism that makes routing trustless is the Hash Time-Locked Contract (HTLC). Alice locks her payment with a hash; the Coffeeshop reveals the preimage to claim it; each hop only collects if it successfully forwards.',
  'At scale, the Lightning Network is a web of channels. Routing algorithms find paths. Payments hop across multiple nodes, each collecting a tiny fee. The blockchain never sees any of it.',
  'Recap — Lightning: open a 2-of-2 multi-sig channel on-chain, trade off-chain with signed balance sheets, close on-chain once. Network routing makes any two people reachable without a direct channel.',
  'Next class preview — Smart Contracts and Ethereum. Bitcoin scripts verify signatures. What if the script could verify anything a general-purpose programming language can express? Ask students to think about what you could build.',
]
